AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
  DisplayCopNames: true
  RunRailsCops: true

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10

Style/SpaceInsideHashLiteralBraces:
  Enabled: false
