AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
  DisplayCopNames: true
  RunRailsCops: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 20
